export const DEFAULT_BOOK_WIDTH = 140;
export const DEFAULT_BOOK_HEIGHT = 220;
export const DEFAULT_TEXT_HORIZONTAL_WIDTH = 160;
export const DEFAULT_TEXT_HORIZONTAL_HEIGHT = 128;
export const DEFAULT_TEXT_VERTICAL_WIDTH = 140;
export const DEFAULT_TEXT_VERTICAL_HEIGHT = 200;
export const DEFAULT_IMAGE_WIDTH = 200;
export const DEFAULT_IMAGE_HEIGHT = 150;
export const DEFAULT_LINK_WIDTH = 240;
export const DEFAULT_LINK_HEIGHT = 160;

export const CANVAS_DIMENSION = 2700;
export const SNAP_THRESHOLD = 10;
export const ALIGNMENT_THRESHOLD = 5;
export const AUTOSAVE_INTERVAL_MS = 7000;
export const TOKEN_REFRESH_INTERVAL_MS = 5 * 60 * 1000;
export const HEARTBEAT_INTERVAL_MS = 60 * 1000;

export const LINK_PREVIEW_API_KEY = '657ab82fe7584749efe812a3b259d48d';

